### ISSUE TITLE
Attack String Length for GCG

### ISSUE THREAD

**Issue by SinHanYang** [UCSB-NLP-Chang/SemanticSmooth#2]
Hi, thanks for updating this repo. In Appendix A.2 of the paper, you mention that the attack string length for GCG is 20 tokens. I was wondering how to control the attack string length for GCG. Thanks!

**Comment by Question406** [comment]
Hi, we did not include the GCG attack code in this repo. To change the attack string length and generate new attack strings, please refer to the original GCG repo: https://github.com/llm-attacks/llm-attacks. Thanks.

**Comment by SinHanYang** [comment]
Thanks for your reply. I can't find the corresponding hyperparameter or function in the GCG codebase to control the attack string length. I am curious about how you did it. Therefore, I will be sincerely grateful if you could provide some information. Thanks.
